apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: connectivity
resources:
  - ../../base
  - externalsecrets.yaml
  - hpa.yaml
  - servicemonitor.yaml
patches:
  - path: service-patch.yaml
    target:
      kind: Service
      name: connectivity-service

images:
  - name: REPOSITORY/connectivity-microservice
    newName: kristianrpo30/connectivity-microservice
    newTag: latest