apiVersion: v1
kind: Service
metadata:
  name: connectivity-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/api/connectivity/metrics"
spec:
  type: ClusterIP