apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: connectivity
resources:
  - namespace.yaml
  - service-account.yaml
  - deployment.yaml
  - consumer-deployment.yaml
  - service.yaml