apiVersion: v1
kind: Service
metadata:
  name: connectivity-service
  namespace: connectivity
  labels:
    app: connectivity-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/api/connectivity/metrics"
spec:
  type: ClusterIP
  selector:
    app: connectivity-service
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http